name: Deploy React Frontend to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js 22
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      # 3. Install dependencies
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      # 4. Build frontend
      - name: Build frontend
        run: |
          cd frontend
          CI=false npm run build
        env:
          REACT_APP_API_URL: "https://final-tq3x.onrender.com"

      # 5. Configure GitHub Pages
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      # 6. Upload build folder as artifact
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './frontend/build'

      # 7. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
